import Button from "@components/button";
import Footer from "@components/footer";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";

const Home: NextPage = () => {
  const connectWallet = () => {
    console.log("connecting");
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="w-full h-[calc(100vh-80px)] text-center flex flex-col">
        <div className="m-auto">
          <Button
            text="Connect Wallet"
            onClick={() => {
              connectWallet();
            }}
          />
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default Home;
